re-regeister controlled component on validation rule change
react-hook-form/react-hook-form pull request #1187
Opened 2020-03-10 16:03 UTC by levente-gal

added useEffect with the validation rules as dependency to re-register field and trigger re-validation if needed

fixes bug: https://github.com/react-hook-form/react-hook-form/issues/1184

2020-03-10 21:35 UTC, bluebill1049 requested changes
Awesome stuff! thank you for your contribution.

2020-03-10 21:35 UTC, bluebill1049 commented on cypress/fixtures/example.json
> +{
i think this should be removed.

2020-03-10 21:35 UTC, bluebill1049 commented on src/controller.test.tsx
> +it('should re-register on new validation rules`', () => {
awesome!

2020-03-10 21:35 UTC, bluebill1049 commented on src/controller.tsx
>    }, [name]);
i would just add `rules` here and remove the logic below. If user want to revalidate give them the option to that at `useEffect`.

2020-03-11 07:35 UTC, levente-gal commented on src/controller.tsx
>    }, [name]);
Can't add rules there because this effect deletes the value of the field because of the `unregister` call in the cleanup of the effect.
I think it cleaner to add another *useEffect* then adding some kind of condition(s) to avoid unregistering.

The validation I think should re-run automatically based on the validation mode set by the user. Think of having a validator based on the value of another field on the form. If the first field changes the validation should re-run automatically on the validated field.

2020-03-11 08:13 UTC, bluebill1049 commented on src/controller.tsx
>    }, [name]);
it's fine to be `unregister` and `re-register` again and the value won't be lost. It's cheap to run anyhow.

2020-03-11 11:53 UTC, levente-gal commented on src/controller.tsx
>    }, [name]);
the value gets lost because of the `useEffect` above: it doesn't find the fieldRef by name (because of the unregister) and it re-registers and set's to the default value

2020-03-11 12:06 UTC, bluebill1049 commented on src/controller.tsx
>    }, [name]);
make sense.

2020-03-11 12:06 UTC, bluebill1049 commented on src/controller.tsx
> +    if (touchedFieldsRef.current[name] && shouldValidate()) {
```suggestion
```

2020-03-11 12:06 UTC, bluebill1049 commented on src/controller.tsx
> +      triggerValidation(name);
```suggestion
```

2020-03-11 12:07 UTC, bluebill1049 commented on src/controller.tsx
> +    }
```suggestion
```

please this trigger validation, and let the user trigger themself.

2020-03-11 12:08 UTC, bluebill1049 commented on src/controller.tsx
> +    }
```suggestion
```

please remove this trigger validation, and let user trigger themself at `useEffect`

2020-03-11 14:36 UTC, levente-gal commented on src/controller.tsx
> +    }
The validation I think should re-run automatically based on the validation mode set by the user. E.g. If an input is required when a checkbox is checked and validation mode is `onChange`. This case I think it would be nice to re-validate the input field when the checkbox changes so the validation message can be shown when checkbox changes.
I don't see why to force the developers to trigger validation it can be triggered by the library. 

In my opinion if the library allows dynamic rules then it should re-validate when the validation rules change.

And without triggering the validation on changed rules the controlled components won't behave similarly to registered ones because the registered ones get re-validated on changed validation rules.

2020-03-11 14:57 UTC, levente-gal commented on src/controller.tsx
> +    }
Please forget my previous message, I was wrong. I remove the trigger validation.

2020-03-11 20:32 UTC, bluebill1049 commented on src/controller.tsx
> +    }
awesome! thanks :) let's get it in.

2020-03-11 20:32 UTC, merged

2020-03-11 20:32 UTC, bluebill1049 commented
Thanks very much for your contribution.