added example for parse and format input value, see #1297
react-hook-form/react-hook-form pull request #1322
Opened 2020-04-02 16:00 UTC by bodokaiser

We added a `parseFormatInputValues.tsx` to `examples/` where we show how
one can implement custom parse and format value behaviour to, for
example, parse a newline-separated list of emails to an array and format
them back to a newline-separated string.

Questions and suggestions:
* [ ] You probably want to fork [my codesandbox][1] to your account?
* [ ] Is the code style used in `examples/parseFormatInputValue.tsx` correct?
* [ ] Is there away to run `examples/parseFormatInputValue.tsx`?

[1]: https://codesandbox.io/s/react-hook-form-parse-and-format-textarea-52dvm

2020-04-02 21:44 UTC, bluebill1049 commented
1.  You probably want to fork my codesandbox to your account? 
happy to use yours, just make sure don't get deleted :)

2020-04-02 21:45 UTC, bluebill1049 commented on examples/parseFormatInputValues.tsx
> +    alert(JSON.stringify(data));
minor: I think `console.log(data)` will do, happy to keep what you got.

2020-04-02 21:45 UTC, bluebill1049 commented on examples/parseFormatInputValues.tsx
> +    <div className="App">
we can remove this wrapper :) less code for the user to read

2020-04-02 21:45 UTC, bluebill1049 commented on examples/parseFormatInputValues.tsx
> +        {errors.emails && (
We have <ErrorMessage /> component.

2020-04-02 21:46 UTC, bluebill1049 requested changes
Awesome stuff! thanks for contributing <3

2020-04-03 04:01 UTC, bluebill1049 approved these changes

2020-04-03 04:01 UTC, merged

2020-04-03 05:48 UTC, bodokaiser commented
Thanks for updating and merging the PR! It was a pleasure to contribute :)