Lint test files and ignore `@ts-ignore` rule within them.
react-hook-form/react-hook-form pull request #1329
Opened 2020-04-03 07:10 UTC by threehams

During the last PR, I noticed that lint errors showed up in-editor, but this wasn't reflected in CI. It took me a bit of time to figure out if this was going to cause the CI checks to fail.

This just overrides the lint rules to allow `ts-ignore` within tests (and allows for other rules to be suppressed over time, as well). That should prevent the disconnect between code and tests for new contributors.

2020-04-03 11:16 UTC, JeromeDeLeon requested changes

2020-04-03 11:16 UTC, JeromeDeLeon commented on .eslintrc.js
> +        // Allow testing runtime errors when not using TS
```suggestion
        // Allow testing runtime errors to suppress TS errors
```

2020-04-03 11:17 UTC, JeromeDeLeon commented on .eslintrc.js
> +        // Allow testing runtime errors when not using TS
I'll allow this, but we should limit using `@ts-ignore` as much as possible.

2020-04-03 11:25 UTC, bluebill1049 commented on .eslintrc.js
> +        // Allow testing runtime errors when not using TS
agree!

2020-04-04 19:53 UTC, threehams commented
hm. I looked at all the `ts-ignore` usages, and none of them are being used for testing invalid input (like I thought they might). I'll get this ready, but then get rid of all the `ts-ignore` in the next commit.

2020-04-04 23:18 UTC, bluebill1049 commented
awesome thanks @threehams! @JeromeDeLeon you happy to approve this PR?

2020-04-05 00:14 UTC, JeromeDeLeon approved these changes

2020-04-05 00:26 UTC, merged