Add an example of forwardRef usage to the Examples
react-hook-form/react-hook-form pull request #1502
Opened 2020-04-26 13:12 UTC by davidkartuzinski

I added an example of how to pass the Ref down to a functional component by wrapping the component in React.forwardRef.

Added a link in the README to a working version of the example on Codesandbox. 

https://codesandbox.io/s/rhfex-en254

Please let me know if any changes are needed.

(I don't know about this TypeScript stuff, but I kept the .tsx file convention to match the docs...)

2020-04-28 11:19 UTC, bluebill1049 commented
sorry for the delay, I will take a look this PR over the weekend 🙏

2020-05-09 02:01 UTC, JeromeDeLeon requested changes
@bluebill1049 Do we have to align every example to the CSS you made for consistency?

@davidkartuzinski LGTM! I only have few notes.

2020-05-09 02:04 UTC, bluebill1049 commented
hey @JeromeDeLeon thanks for the review ❤️ I think the example is good but need some trim to keep it more focus on the API, i am busy working on v6 and i will come in and trim it later on.

2020-05-09 02:10 UTC, JeromeDeLeon commented
No worries. :sweat_smile:

2020-05-10 12:23 UTC, davidkartuzinski commented on examples/forwardRefToPassRefProp.tsx
> +const MyButton = ({ type, id, value, form, children }) => {
@JeromeDeLeon - I can make the changes. I get that we want to make this more succinct. I can leave just the email input, and keep a simple button (per your example).  Is this what you had in mind?

2020-05-10 12:28 UTC, davidkartuzinski commented on examples/forwardRefToPassRefProp.tsx
> +    event.target.reset(); // reset the form after submission
@JeromeDeLeon - Here you want to remove the onBlur and the reset function from the onSubmit?

2020-05-10 12:29 UTC, JeromeDeLeon commented on examples/forwardRefToPassRefProp.tsx
> +    event.target.reset(); // reset the form after submission
What do you mean bu that?

2020-05-10 12:32 UTC, JeromeDeLeon commented on examples/forwardRefToPassRefProp.tsx
> +const MyButton = ({ type, id, value, form, children }) => {
If you could make it as simple as possible that would be great and also if possible, you could change the style so that it follows other examples' style as well. Thanks.

2020-05-10 12:57 UTC, bluebill1049 commented
I have made some cleanup, let me know if that's ok. I am trying to focus on an example.

2020-05-11 00:45 UTC, merged

2020-05-11 00:45 UTC, bluebill1049 commented
Thanks for the contribution : )

2020-05-11 03:31 UTC, kotarella1110 commented
TS example:

```ts
import * as React from "react";
import { useForm } from "react-hook-form";

const Input = React.forwardRef(
  (
    props: React.DetailedHTMLProps<
      React.InputHTMLAttributes<HTMLInputElement>,
      HTMLInputElement
    >,
    ref: React.Ref<HTMLInputElement>
  ) => {
    return <input ref={ref} {...props} />;
  }
);

export default function App() {
  const { register, handleSubmit } = useForm<{
    firstName: string;
    lastName: string;
  }>();
  const onSubmit = handleSubmit((data, event) => {
    console.log(data);
  });

  return (
    <form onSubmit={onSubmit}>
      <Input ref={register} name="firstName" />
      <Input ref={register} name="lastName" />

      <input type="submit" />
    </form>
  );
}
```

2020-05-11 03:34 UTC, bluebill1049 commented
@kotarella1110 i will add this in our new page :)

2020-05-11 03:39 UTC, kotarella1110 commented
We can use forwardRef with generics.

```ts
import * as React from "react";
import { useForm } from "react-hook-form";

const Input = React.forwardRef<
  HTMLInputElement,
  React.DetailedHTMLProps<
    React.InputHTMLAttributes<HTMLInputElement>,
    HTMLInputElement
  >
>((props, ref) => {
  return <input ref={ref} {...props} />;
});

export default function App() {
  const { register, handleSubmit } = useForm<{
    firstName: string;
    lastName: string;
  }>();
  const onSubmit = handleSubmit((data, event) => {
    console.log(data);
  });

  return (
    <form onSubmit={onSubmit}>
      <Input ref={register} name="firstName" />
      <Input ref={register} name="lastName" />

      <input type="submit" />
    </form>
  );
}
```

2020-05-11 03:41 UTC, bluebill1049 commented
even better!

2020-05-11 18:13 UTC, davidkartuzinski commented on examples/forwardRefToPassRefProp.tsx
> +const MyButton = ({ type, id, value, form, children }) => {
I was too slow. @bluebill1049 already made revisions to the example.

2020-05-11 18:14 UTC, davidkartuzinski commented on examples/forwardRefToPassRefProp.tsx
> +    event.target.reset(); // reset the form after submission
@JeromeDeLeon - I was just asking if I would remove the mode: onBlur and the functionality to reset the forms as these are part of React Hook Form but not part of ForwardRef. Anyway @bluebill1049 made some changes and removed these.