#1580 attempt with render props API
react-hook-form/react-hook-form pull request #1711
Opened 2020-05-27 10:46 UTC by bluebill1049

2020-05-27 12:30 UTC, bluebill1049 commented
Let me know what your guys think please, thanks for @kotarella1110's suggestion.

2020-05-27 16:27 UTC, kotarella1110 requested changes
I think it's better to remove `as` prop, leaving only render prop.
The reason is that if you use as prop, we need to leave `onBlur`, `onChange`, `onChangeName`, `onBlurName`, `onBlur`, `valueName` props.

```ts
export type ControllerProps<TControl extends Control = Control> = {
  name: FieldName<FieldValuesFromControl<TControl>>;
  as?: React.ReactElement;
  rules?: ValidationOptions;
  onFocus?: () => void;
  onBlur?: EventFunction;
  onChangeName?: string;
  onBlurName?: string;
  valueName?: string;
  render?: (data: {
    handleChange: EventFunction;
    handleBlur: EventFunction;
    value: any;
  }) => React.ReactElement;
  defaultValue?: unknown;
  control?: TControl;
};
```

What if we want to customize the return value? We should use `onChange` prop.

```ts
<Controller
  name="test" 
  control={control}
  as={<CustomInput />}
  onChange={(e, value) => value}
/>
```

What if the `onChange` event name is `onTextChange`? We should use `onChangeName` prop.

```ts
<Controller
  name="test" 
  control={control}
  as={<CustomInput />}
  onChange={(e, value) => value}
  onChangeName="onTextChange"
/>
```

If we have only render prop, `Controller` don't need these props.

```ts
export type ControllerProps<TControl extends Control = Control> = {
  name: FieldName<FieldValuesFromControl<TControl>>;
  rules?: ValidationOptions;
  onFocus?: () => void;
  render: (data: {
    handleChange: EventFunction;
    handleBlur: EventFunction;
    value: any;
  }) => React.ReactElement;
  defaultValue?: unknown;
  control?: TControl;
};
```

```ts
<Controller 
  name="test" 
  control={control} 
  render={({ handleChange, handleBlur, value}) => <CustomInput
      value={value}
      onTextChange={(e, value) => value}
      onBlur={handleBlur}
    />
/>
```

With render props only, it's simpler with fewer props.
RHF users can also easily predict what they are doing in the controller by passing event handlers or values ​​to the Controlled Component (`<ControlledComponent value={value} onChange={handleChange} onBlur={handleBlur} />`).

Note: I understand that removing `as` prop is a breaking change and will impact existing users.

2020-05-27 16:27 UTC, kotarella1110 commented on src/controller.tsx
> +  };
I think you need to do the following to make the onBlur event handleable by the user:

https://codesandbox.io/s/react-hook-form-issue-1580-59soi?file=/src/src/controller.tsx:2544-3180

```ts
const commonBlurTask = () => {
  if (
    readFormStateRef.current.touched &&
    !get(touchedFieldsRef.current, name)
  ) {
    set(touchedFieldsRef.current, name, true);
    reRender();
  }

  if (shouldReValidateOnBlur) {
    trigger(name);
  }
};

function handleBlur(...args: any): void;
function handleBlur(handler: EventFunction): (...args: any) => void;
function handleBlur(handlerOrArgs: any): ((...args: any) => void) | void {
  if (typeof handlerOrArgs !== 'function') {
    commonBlurTask();
  }
  return (...args: any) => {
    handlerOrArgs(args);
    commonBlurTask();
  };
}
```

```ts
<Controller 
  name="test" 
  control={control} 
  render={({ handleChange, handleBlur, value}) => <CustomInput
      value={value}
      onChange={handleChange}
      onBlur={handleBlur((...args) => { console.log(args) })}
    />
/>
```

2020-05-27 22:22 UTC, bluebill1049 commented
Thanks, @kotarella1110 I think what I refer is to use either, maybe `as` should rename to `element` like react-router. so the user still gets easy to use (if nothing onChange, onBlur, doesn't need to be renamed).

2020-05-27 22:23 UTC, bluebill1049 commented
I did a similar thing with `react-simple-animate`. users can use the following syntax
```
<Animate>Test</Animate>

<Aniamte render={} /> // if you want to customise the dom node
```

2020-05-27 22:28 UTC, bluebill1049 commented on src/controller.tsx
> +    setValue(name, commonTask(event), shouldValidate());
Yes, you are right, please commit that change. 🙏  (to my branch)

2020-05-27 22:29 UTC, bluebill1049 commented on src/controller.tsx
> +  };
we don't really worry about what's return by `onBlur`.

2020-05-28 00:01 UTC, kotarella1110 commented on src/controller.tsx
> +  };
OK. If RHF users wants to do something in the blur event, they need to do the following:

```ts
<Controller 
  name="test" 
  control={control} 
  render={({ handleChange, handleBlur, value}) => <CustomInput
      value={value}
      onChange={handleChange}
      onBlur={(e) => {
        // do something here
        // console.log(e)
        handleBlur(e)
      }}
    />
/>
```

2020-05-28 00:02 UTC, kotarella1110 commented on src/controller.tsx
> +    setValue(name, commonTask(event), shouldValidate());
@bluebill1049 I will fix 👍

2020-05-28 00:03 UTC, bluebill1049 commented
after @stramel 's feedback I think the following is best:

```
// Supported
<Controller name="test" control={control} render={<TextFields myUniqueProp={state} />} />
<Controller name="test" control={control} render={({onChange, onBlur, ...props}) => <TextFields handleChange={onChange} handleBlur={onBlur} {..props} />} />
```

2020-05-28 00:03 UTC, bluebill1049 commented on src/controller.tsx
> +  };
yes, we should document that.

2020-05-28 00:07 UTC, kotarella1110 commented
@bluebill1049 if rename handleChange to onChange and handleBlur to onBlur, user can simplify the code.

```diff
export type ControllerProps<TControl extends Control = Control> = {
  name: FieldName<FieldValuesFromControl<TControl>>;
  rules?: ValidationOptions;
  onFocus?: () => void;
  render: (data: {
-    handleChange: EventFunction;
+   onChange: EventFunction;
-    handleBlur: EventFunction;
+   onBlur: EventFunction;
    value: any;
  }) => React.ReactElement;
  defaultValue?: unknown;
  control?: TControl;
};
```

```ts
<Controller 
  name="test" 
  control={control} 
  render={(props) => <CustomInput {...props} />
/>
```

2020-05-28 00:10 UTC, bluebill1049 commented
love it @kotarella1110!

2020-05-28 00:11 UTC, bluebill1049 commented
> after @stramel 's feedback I think the following is best:
> 
> ```
> // Supported
> <Controller name="test" control={control} render={<TextFields myUniqueProp={state} />} />
> <Controller name="test" control={control} render={({onChange, onBlur, ...props}) => <TextFields handleChange={onChange} handleBlur={onBlur} {..props} />} />
> ```

what do you think about this proposal @kotarella1110 ?

2020-05-28 00:20 UTC, JeromeDeLeon commented
I assumed this fix the TS that's why we want to provide render props, am I right? @bluebill1049  @kotarella1110

2020-05-28 00:22 UTC, bluebill1049 commented
> I assumed this fixes the TS that's why we want to provide render props, am I right? @bluebill1049 @kotarella1110

That's the origin, but at the same time, I think this will improve the API.

2020-05-28 00:26 UTC, stramel commented
Do we have preference on the prop name? 

`as`, `render`, `element`, `input` or other suggestions?

2020-05-28 00:29 UTC, JeromeDeLeon commented
I agreed with all the decision of @kotarella1110 , like we should really remove `as` as this will not be necessary anymore unless there's a fix to it for TS. As for @stramel's idea, 

```jsx
<Controller name="test" control={control} render={<TextFields myUniqueProp={state} />} />

// is the same as below?

<Controller name="test" control={control} as={<TextFields myUniqueProp={state} />} />
```

Is there any reason for supporting it in `render` prop? Just asking :wink:

I've come to like this idea of `render` thing. :smile:

2020-05-28 00:40 UTC, bluebill1049 commented
> Do we have preference on the prop name?
> 
> `as`, `render`, `element`, `input` or other suggestions?

I think `render` is pretty standard for render props. probably have to change `ErrorMessage` to follow this as well.

2020-05-28 00:42 UTC, bluebill1049 commented
> I agreed with all the decision of @kotarella1110 , like we should really remove `as` as this will not be necessary anymore unless there's a fix to it for TS. As for @stramel's idea,
> 
> ```js-jsx
> <Controller name="test" control={control} render={<TextFields myUniqueProp={state} />} />
> 
> // is the same as below?
> 
> <Controller name="test" control={control} as={<TextFields myUniqueProp={state} />} />
> ```
> 
> Is there any reason for supporting it in `render` prop? Just asking 😉
> 
> I've come to like this idea of `render` thing. 😄

Yes, I agree.

what about the following option:
```
<Controller name="test" control={control} render={<TextFields myUniqueProp={state} />} />
<Controller name="test" control={control} render={({onChange, onBlur, ...props}) => <TextFields handleChange={onChange} handleBlur={onBlur} {..props} />} />
```

so if users don't require any prop wiring, they can just use slot it in without the need to render props.

2020-05-28 00:54 UTC, JeromeDeLeon commented
I haven't seen any cases where below applies, I have only seen `render function` so far.

```jsx
<Controller name="test" control={control} render={<TextFields myUniqueProp={state} />} />
```

2020-05-28 01:00 UTC, JeromeDeLeon commented
Though the reason is valid :) We could move it out to `element` prop like you said.

2020-05-28 01:02 UTC, bluebill1049 commented
Happy to listen everyone's thoughts, I just thought to render prop is convenient when you need to wire those onChange and value, for standard stuff `render={<TextField />}` is short and sweet. I think most people try to follow the pattern expose `value`, `onBlur` and `onChange`.

2020-05-28 01:06 UTC, stramel commented
The main thing that I'm worried about is the typing on the element without the render props. It may have to be render props or component. That would allow it to be short and sweet.

2020-05-28 01:07 UTC, JeromeDeLeon commented
I'm good with using `render` like what @stramel suggested. :smile:

2020-05-28 01:10 UTC, bluebill1049 commented
> The main thing that I'm worried about is the typing on the element without the render props. It may have to be render props or component. That would allow it to be short and sweet.

Yes, i agree, 

Props `render` support `renderProps` or `component` is the best, short and sweet.

2020-05-28 01:12 UTC, stramel commented
I also like the fact this cuts a few bytes off the size.

2020-05-28 01:35 UTC, bluebill1049 commented
let me know your thoughts as well @kotarella1110 if we can all align, I will proceed with the change.

2020-05-28 01:43 UTC, kotarella1110 commented
`render={<CustomInput />}` is very simple.
But if `onChange` is required in the `CustomInput`'s props, it will cause type error.

```ts
type CustomInput = {
  onChange: (e: any) => any; // required
};
<Controller name="test" control={control} render={<CustomInput />} /> // type error
```

2020-05-28 01:46 UTC, bluebill1049 commented
> `render={<CustomInput />}` is very simple.
> But if `onChange` is required in the `CustomInput`'s props, it will cause type error.
> 
> ```ts
> type CustomInput = {
>   onChange: (e: any) => any; // required
> };
> <Controller name="test" control={control} render={<CustomInput />} /> // type error
> ```

I think if it's required, then user has the opportunity to use `renderProps`. I guess it's optional.

2020-05-28 01:48 UTC, bluebill1049 commented
I think this will tick both boxes, in terms of simplicity and type support.

2020-05-28 01:50 UTC, stramel commented
Yeah, I was trying to come up with a solution around it but I think the only way would be to do component.

So I think everyone is in agreement?

```
// Support

render={MyInput}
render={({ onChange, onBlur, value, ...props }) => <MyInput handleChange={onChange} handleBlur={onBlur} myValue={value} {...props} customProp={state.isCustom} />}
```

2020-05-28 01:51 UTC, kotarella1110 commented
> Yeah, I was trying to come up with a solution around it but I think the only way would be to do component.
> 
> So I think everyone is in agreement?
> 
> ```
> // Support
> 
> render={MyInput}
> render={({ onChange, onBlur, value, ...props }) => <MyInput handleChange={onChange} handleBlur={onBlur} myValue={value} {...props} customProp={state.isCustom} />}
> ```

awesome! all OK!

2020-05-28 01:52 UTC, bluebill1049 commented
I will start working on it tonight, but feel free to commit to my branch. if you find the thing is missing and incorrect.

2020-05-28 02:37 UTC, bluebill1049 commented
maybe we should fix ErrorMessage as well, so the API is consistent. 

```
<ErrorMessage render={} />
```

and remove `children` and `as` props.

2020-05-28 02:47 UTC, kotarella1110 commented
> @kotarella1110 maybe we should fix ErrorMessage as well, so the API is consistent.
> 
> ```
> <ErrorMessage render={} />
> ```
> 
> and remove `children` and `as` props.

I agree with you.
This is OK?

```ts
// not support
<ErrorMessage render={CustomMessage} />
// support
<ErrorMessagee rennder={({ message }) => <CustomMessage>{message}</CustomMessage>} />
```

2020-05-28 03:00 UTC, bluebill1049 commented
yea sounds good @kotarella1110 consistent API is great.

2020-05-28 03:25 UTC, kotarella1110 commented
I will fix ErrorMessage component 👍

2020-05-28 06:41 UTC, bluebill1049 commented on src/controller.tsx
> +    <InnerComponent {...props} />
we can't use `clone`?

2020-05-28 06:42 UTC, bluebill1049 commented on src/controller.tsx
> +  return isReactComponentClass(InnerComponent) ? (
do we need this check? or `isValidElement` is good enough?

2020-05-28 07:05 UTC, bluebill1049 commented on src/utils/isReactComponentClass.ts
> +export default (component: any): component is React.ComponentClass<any> =>
will `isValidElement` enough for the check instead of this utility function?

2020-05-28 07:24 UTC, bluebill1049 commented on src/controller.tsx
> +  return isReactComponentClass(InnerComponent) ? (
hmmm i see <Test /> will return false. is there any better way then the function below?

2020-05-28 07:30 UTC, bluebill1049 commented on src/controller.tsx
> +  return isReactComponentClass(InnerComponent) ? (
https://codesandbox.io/s/unruffled-mahavira-x5hnw?file=/src/App.js it doesn't really work.

2020-05-28 07:41 UTC, kotarella1110 commented on src/controller.tsx
> +  return isReactComponentClass(InnerComponent) ? (
`isReactComponentClass` is is a function that validates a class component.

```ts
class ClassComponent extends React.Component {
  render() {
    return <div />;
  }
}

const FunctionComponent = () => {
  return <div />;
};

isReactComponentClass(ClassComponent) // true
isReactComponentClass(FunctionComponent) // true
```

https://codesandbox.io/s/silly-chaplygin-tb74k

2020-05-28 07:44 UTC, bluebill1049 commented on src/controller.tsx
> +  return isReactComponentClass(InnerComponent) ? (
sorry, why are we testing for Class component?

2020-05-28 07:47 UTC, kotarella1110 commented on src/controller.tsx
> +        ...rest,
I don't think rest props are unnecessary. I think users should use render prop if they want to pass custom props to `ControlledComponent`.

```ts
type CustomInputProps = {
  custom: string;
  onChange?: (...args: any[]) => any;
  onBlur?: (...args: any[]) => any;
  value?: string;
}

<Controller 
  name="test" 
  control={control} 
  render={(props) => <CustomInput {...props} custom="custom" />
/>
```

2020-05-28 07:50 UTC, bluebill1049 commented on src/controller.tsx
> +        ...rest,
what if user just wants to add a className?

`<Controller className="test" name="test" control={control} />`

2020-05-28 07:53 UTC, kotarella1110 commented on src/controller.tsx
> +  return isReactComponentClass(InnerComponent) ? (
`React.ComponentType` is union of `React.ComponentClass` and `React.FunctionComponent`.


```ts
type React.ComponentType<P = {}> = React.ComponentClass<P, any> | React.FunctionComponent<P>
```

The Controlled Input may also be a Class Component.

2020-05-28 07:55 UTC, bluebill1049 commented on src/controller.tsx
> +  return isReactComponentClass(InnerComponent) ? (
but the check right now said if it's a class component do <Xxxx /> otherwise render props?

2020-05-28 08:04 UTC, JeromeDeLeon commented on src/controller.tsx
> +        ...rest,
Like what @stramel said
> ```
> // Support
> 
> render={MyInput}
> render={({ onChange, onBlur, value, ...props }) => <MyInput handleChange={onChange} handleBlur={onBlur} myValue={value} {...props} customProp={state.isCustom} />}
> ```

If we would support passing `MyInput` directly then we need `rest` but for me since we now have render props, I will leave everything to the `InnerComponent` instead of passing it to `Controller`. Just my opinion though.

2020-05-28 08:05 UTC, kotarella1110 commented on src/controller.tsx
> +  return isReactComponentClass(InnerComponent) ? (
@bluebill1049 Yes. Just as you said.

2020-05-28 08:06 UTC, kotarella1110 commented on src/controller.tsx
> +        ...rest,
I think user should do the following:

```ts
<Controller 
  name="test" 
  control={control} 
  render={(props) => <CustomInput {...props} className="test" />
/>
```

2020-05-28 08:07 UTC, JeromeDeLeon commented on src/controller.tsx
> +  return isReactComponentClass(InnerComponent) ? (
Couldn't we just check if it's a component, because either way they are both component that can be rendered on screen right?

2020-05-28 08:08 UTC, bluebill1049 commented on src/controller.tsx
> +        ...rest,
hmmm, I think mixed with `Component ` with `render props` sounds good on paper, but during implementation is not great, especially with the `component` type check that @kotarella1110 introduced. I think maybe we should make a decision on the following

1. use two props `as` or `render`
con: two props
pro: we still have good DX with `as` when a component is simple

2. use render props only
con: lost the DX with a simple component
prop:  less headache and easy to implement.

2020-05-28 08:11 UTC, bluebill1049 commented on src/controller.tsx
> +  return isReactComponentClass(InnerComponent) ? (
yes, @JeromeDeLeon that's what I am after here, we shouldn't differentiate Class vs Functional component. but after reading through StackOverflow, 

it's not a simple check. https://stackoverflow.com/questions/33199959/how-to-detect-a-react-component-vs-a-react-element

2020-05-28 08:13 UTC, kotarella1110 commented on src/controller.tsx
> +        ...rest,
I agree with the second proposal.

2020-05-28 08:15 UTC, bluebill1049 commented on src/controller.tsx
> +        ...rest,
How about this plan? Let's go all the way with `render props` first. Then worry about component after. at least we nail one goal first before the other.

2020-05-28 08:16 UTC, bluebill1049 commented on src/controller.tsx
> +        ...rest,
if people miss `as` we can introduce it again and it won't be **type** safe.

2020-05-28 08:23 UTC, bluebill1049 commented on src/controller.tsx
> +        ...rest,
make sure you do a code review on this PR when it's ready @JeromeDeLeon. this is your territory that we are messing around 👍

2020-05-28 08:24 UTC, bluebill1049 commented on src/controller.tsx
> +        ...rest,
sorry for taking the wrong direction and wasting your effort @kotarella1110 😭

2020-05-28 08:34 UTC, kotarella1110 commented on src/controller.tsx
> +        ...rest,
@bluebill1049 do not worry 👍

2020-05-28 08:35 UTC, JeromeDeLeon commented on src/utils/isReactComponentClass.ts
> +export default (component: any): component is React.ComponentClass<any> =>
Shouldn't be just return a boolean? I just tried it with codesandbox and it returns an object.

2020-05-28 08:38 UTC, bluebill1049 commented on src/utils/isReactComponentClass.ts
> +export default (component: any): component is React.ComponentClass<any> =>
this is removed :)

2020-05-28 08:42 UTC, JeromeDeLeon commented on src/controller.tsx
> +        ...rest,
Will do. Later tonight.

2020-05-28 08:58 UTC, JeromeDeLeon commented on src/controller.tsx
> +  return isReactComponentClass(InnerComponent) ? (
Yes, I also read that one and think that it's not as simple as it is.

2020-05-28 08:59 UTC, bluebill1049 commented on src/controller.tsx
> +      : setValue(name, commonTask(...callbackOrEvent), shouldValidate());
@kotarella1110 can you review what I did?

2020-05-28 09:49 UTC, kotarella1110 commented on src/controller.tsx
> +      : setValue(name, commonTask(...callbackOrEvent), shouldValidate());
@bluebill1049 wow! greate! Thanks.
Does `getInputValue` inside `commonTask` work correctly if this is multiple event args?

2020-05-28 09:53 UTC, kotarella1110 commented on src/controller.tsx
> +      : setValue(name, commonTask(...callbackOrEvent), shouldValidate());
I missed this commit (https://github.com/react-hook-form/react-hook-form/pull/1711/commits/a93e713e9f1f870ca5d6c3821d7b31c89b961772). I think it works correctly 💯

2020-05-28 09:57 UTC, bluebill1049 commented
create another PR to support both 
`as` and `render` consider we are already doing with `ErrorMessage`. so we can keep API consistent with support `as` and `render` obviously `as` will have an issue with required type, so use `render props` to avoid issues like that, however, we still can provide flexibility to users. This also leads to a minimum change to ErrorMessage as well, the only thing to change is `children` to `render`.

2020-05-28 23:30 UTC, bluebill1049 commented
Lost a few hrs of sleep last night to think over this API, here are my thoughts and feel free to raise your objection.

This PR is trigger by `Type` related issue which cause by `as` which makes sense to provider solution with this with render prop, but it doesn't/shouldn't mean we should kill the flexible with `as`. 

--------

- `as` will be remained for simple usage assume most of the external component does follow standard component, which is exposed with `onChange` and `value` as optional not required type.
- `onChange, onChangeName, onBlur, onBlurName, valueName` will be remmoved
- render props to support custom methods to support those methods have been removed.

2020-05-28 23:43 UTC, JeromeDeLeon commented
Could you show a sample snippet of using `as` and `render` props?

2020-05-28 23:45 UTC, bluebill1049 commented
> Could you show a sample snippet of using `as` and `render` props?

They don't work together, just like ErrorMessage. you use either `as` or `render`

```tsx
<Controller as={TextField} control={control} name="test" />
```

or

```tsx
<Controller render={props => <TextField {...props} />} control={control} name="test" />
```

2020-05-29 00:40 UTC, JeromeDeLeon commented
I understand your decision and seems valid for me. The only difference I could see is customization. `as` prop works out of the box while keeping the simplicity to use and `render` prop is for customization but I could only see myself using the `as` prop as I don't have any use cases for customization right now aside when `onChangeName` or `valueName` is different and even the introduction of below snippet, I still prefer to write it like what you did above.

```jsx
<Controller as={<CustomInput />} />

// I still prefer it this way,
<Controller as={CustomInput} />
```

2020-05-29 00:45 UTC, bluebill1049 commented
> I understand your decision and seems valid for me. The only difference I could see is customization. `as` prop works out of the box while keeping the simplicity to use and `render` prop is for customization but I could only see myself using the `as` prop as I don't have any use cases for customization right now aside when `onChangeName` or `valueName` is different and even the introduction of below snippet, I still prefer to write it like what you did above.
> 
> ```js-jsx
> <Controller as={<CustomInput />} />
> 
> // I still prefer it this way,
> <Controller as={CustomInput} />
> ```

For this part we will keep API as what we have today:

```
// all valid
<Controller as={<CustomInput />} />
<Controller as={"input"} />
<Controller as={CustomInput} />
```

2020-05-29 01:02 UTC, stramel commented
Wait since this is for v6, why are we not removing the `as`?

2020-05-29 01:04 UTC, bluebill1049 commented
> Wait since this is for v6, why are we not removing the `as`?

because of its simplicity as I have demonstrated above. ErrorMessage shares the same usage with `as` and `render`.

2020-05-29 01:24 UTC, stramel commented
Why do we need both props? That will just result in a confusing API. The simplicity can still remain. The single prop can cover all cases.

Personally, I very much dislike the string use-case. I don't really see a benefit to it.

2020-05-29 01:32 UTC, bluebill1049 commented
> Why do we need both props? That will just result in a confusing API. The simplicity can still remain since the single prop can cover all cases.
> 
> Personally, I very much dislike the string use-case. I don't really see a benefit to it.

I understand your concern with `as` with string, and so does is an optional and personal preference thing.

2020-05-29 01:36 UTC, JeromeDeLeon commented
> Why do we need both props? That will just result in a confusing API. The simplicity can still remain since the single prop can cover all cases.
> 
> Personally, I very much dislike the string use-case. I don't really see a benefit to it.

I see, I do think string-case is invalid because `Controller` is for Custom Component that doesn't support ref and string-case like `input`, `select`, `textarea` doesn't need `Controller` at all at makes thing more complicated. We could omit the support for string-case here or DOMElement.

2020-05-29 01:44 UTC, bluebill1049 commented
I am also looking at the API at the wholist point of view.

remove `as` means we need to remove `as` at `ErrorMessage`, and I still believe as is the simplest way to render an error message at `ErrorMessage`, some users may prefer `as` with its simplicity and some will have to force to use `renderProps` for the sake of custom event name. I think give people the option is not the bad thing, it shouldn't create too much confusion for the API. 

it's simple as using `as` if you don't need to configure anything, otherwise use render props to wire it up yourself.

2020-05-29 03:55 UTC, kotarella1110 commented
> `render={<CustomInput />}` is very simple.
> But if `onChange` is required in the `CustomInput`'s props, it will cause type error.
> 
> ```ts
> type CustomInput = {
>   onChange: (e: any) => any; // required
> };
> <Controller name="test" control={control} render={<CustomInput />} /> // type error
> ```

@bluebill1049 If the above issue occurs, is this solution users need to use `React.ComponetType` or render prop as below?

```ts
<Controller name="test" control={control} as={CustomInput} />
```

or

```ts
<Controller name="test" control={control} render={props => <CustomInput {...props} />} />
```

2020-05-29 04:03 UTC, bluebill1049 commented
> > `render={<CustomInput />}` is very simple.
> > But if `onChange` is required in the `CustomInput`'s props, it will cause type error.
> > ```ts
> > type CustomInput = {
> >   onChange: (e: any) => any; // required
> > };
> > <Controller name="test" control={control} render={<CustomInput />} /> // type error
> > ```
> 
> @bluebill1049 If the above issue occurs, is this solution users need to use `React.ComponetType` or render prop as below?
> 
> ```ts
> <Controller name="test" control={control} as={CustomInput} />
> ```
> 
> or
> 
> ```ts
> <Controller name="test" control={control} render={props => <CustomInput {...props} />} />
> ```

Simple usage stays with `as`:

```
<ErrorMessage as={<StyledParagraph />} errors={errors} />
<Controller as={<TextField} />} name="test" control={control} />
```

Type error or custom node structure use render props

```
<ErrorMessage errors={errors} render={({ message }) => {
  <div><span className="error">{message}</span></div>
}} />
<Controller 
  name="test" 
  control={control} 
  render={props => <div><CustomInput {...props} /></div>}
/>
````

2020-05-29 04:11 UTC, kotarella1110 commented
@bluebill1049 Do you not support `React.ComponetType` and `keyof JSX.IntrinsicElements`?

```ts
// not support?
<Controller as={TextField} name="test" control={control} />
```

2020-05-29 04:21 UTC, bluebill1049 commented
> @bluebill1049 Do you not support `React.ComponetType` and `keyof JSX.IntrinsicElements`?
> 
> ```ts
> // not support?
> <Controller as={TextField} name="test" control={control} />
> ```
> 
> Also, do you support rest props?
> 
> ```ts
> <Controller as={<TextField />} name="test" control={control} custom="custom" />
> ```

What you and @JeromeDeLeon have done with the Controller will stay as it is for today (a little less breaking change for the existing users), except we will only remove `onChangeName`, `onBlurName`, `valueName` and replaced with render props approach.

2020-05-29 04:57 UTC, stramel commented
I still really don't like the idea of offering both `as` and `render`. The API is not intuitive. What happens when I pass both props?

2020-05-29 04:59 UTC, bluebill1049 commented
> I still really don't like the idea of offering both `as` and `render`. The API is not intuitive. What happens when I pass both props?

That's what we have inside ErrorMessage:

```
  return InnerComponent ? (
    React.isValidElement(InnerComponent) ? (
      React.cloneElement(InnerComponent, props)
    ) : (
      React.createElement(InnerComponent as string, props)
    )
  ) : (
    <React.Fragment {...props} />
  );
```

2020-05-29 05:03 UTC, bluebill1049 commented
In fact, `as` is used by `styled-component` and `chakra UI` as well.

Take an example here:
 
```
<Box as="button" rounded="md" bg="tomato" color="white" px={4} h={8} />
```

<Box as="button" rounded="md" bg="tomato" color="white" px={4} h={8}>
  {YourContent}
</Box>
```

2020-05-29 05:13 UTC, bluebill1049 commented
This Component is been there for a while: I didn't hear people complain about the usage just yet: https://react-hook-form.com/api#ErrorMessage

2020-05-29 05:21 UTC, bluebill1049 commented
Look away from Controller for a sec, what about ErrorMessage

```
<ErrorMessage as={StyledError} name="Test" />

<ErrorMessage render={({ message }) => <StyledError>{message}</StyledError>} name="Test" /> //how inconvient it is for something simple
```

2020-05-29 05:53 UTC, bluebill1049 commented
shared a vote on twitter: https://twitter.com/HookForm/status/1266240189195669505 decision will be made by tmr after the vote.

2020-05-29 06:19 UTC, bluebill1049 commented
If we can easily diff between `callback` and `component` with `render`, then it's good to move ahead, but reality the check is not great and pretty.

2020-05-29 06:32 UTC, stramel commented
Is there a reason that we need to check? Can't we just call the function using `createElement`? In reality, it's just an inline component...

2020-05-29 06:34 UTC, bluebill1049 commented
> Is there a reason that we need to check? Can't we just call the function using `createElement`? In reality, it's just an inline component...

can you elaborate on this? 
```
render={() => {}}
render={Test}
```
how can we know which one to use React.createElement()?

2020-05-29 06:41 UTC, stramel commented
Isn't all of this essentially equal?

```
const Test = () => <input />
render={Test}
```

vs

```
render={() => <input />}
```

It's essentially an inline component.

2020-05-29 06:43 UTC, bluebill1049 commented
> Isn't all of this essentially equal?
> 
> ```
> const Test = () => <input />
> render={Test}
> ```
> 
> vs
> 
> ```
> render={() => <input />}
> ```
> 
> It's essentially an inline component.

where are all the `props`?

2020-05-29 06:45 UTC, bluebill1049 commented
> Isn't all of this essentially equal?
> 
> ```
> const Test = () => <input />
> render={Test}
> ```
> 
> vs
> 
> ```
> render={() => <input />}
> ```
> 
> It's essentially an inline component.

I think you are right, we can always just do `React.creatElement('xxx', props)`, it doesn't need a check.

2020-05-29 06:46 UTC, JeromeDeLeon commented
[Codesandbox](https://codesandbox.io/s/suspicious-wing-d9n1f?file=/src/App.js) I tried it, @stramel was right. I didn't know that.

2020-05-29 06:47 UTC, stramel commented
It's late here but I will post some more detailed thoughts in the morning

2020-05-29 06:48 UTC, JeromeDeLeon commented
Thanks @stramel I learned new stuff today :confetti_ball:

2020-05-29 06:48 UTC, bluebill1049 commented
> It's late here but I will post some more detailed thoughts in the morning

I didn't proceeds with render for all because all the `React.prototype` check. This is great! my god wasted almost 1 day discuss this...

2020-05-29 06:50 UTC, JeromeDeLeon commented
I must say this discussion is worthwhile. I enjoyed being part of this.

2020-05-29 06:51 UTC, bluebill1049 commented
i guess this is what we after?

```
return React.createElement(render, {
    onChange,
    onBlur,
    value,
});
```

2020-05-29 06:54 UTC, JeromeDeLeon commented
We could even passed the `name` and `controller`

2020-05-29 06:55 UTC, bluebill1049 commented
> We could even passed the `name` and `controller`

what do you mean?

2020-05-29 07:00 UTC, JeromeDeLeon commented
I mean below snippet. I saw that you passed the `control` and `name` instead of putting it inside `props` or that doesn't make sense?

> ```tsx
> <Controller render={props => <TextField {...props} />} control={control} name="test" />
> ```

2020-05-29 07:08 UTC, bluebill1049 commented
> I mean below snippet. I saw that you passed the `control` and `name` instead of putting it inside `props` or that doesn't make sense?
> 
> > ```tsx
> > <Controller render={props => <TextField {...props} />} control={control} name="test" />
> > ```

Below looks right to me.
`<Controller render={props => <TextField {...props} />} control={control} name="test" />`

2020-05-29 07:28 UTC, bluebill1049 commented
ok running into the same problem again...

<img width="583" alt="Screen Shot 2020-05-29 at 5 28 17 pm" src="https://user-images.githubusercontent.com/10513364/83233279-d27f0d00-a1d1-11ea-8432-5133765a3916.png">
<img width="591" alt="Screen Shot 2020-05-29 at 5 28 09 pm" src="https://user-images.githubusercontent.com/10513364/83233289-d579fd80-a1d1-11ea-8e2e-40f1ddc0468b.png">

2020-05-29 07:37 UTC, JeromeDeLeon commented
Tell me if I'm wrong, but to my understanding, `control` is only being used inside `Controller` and not the `InnerComponent`, that's why we never passed it to `props` right?

For `name`, not all Components support `name` prop like `react-select`.

For `Controller`'s use case:

```jsx
<Controller
  control={control}
  name="reactSelect"
  render={({ onChange, ...restProps }) => (
    <Select
      {...restProps}
      onChange={onChange(selected => selected)}
      options={options}
    />
  )}
/>
```

2020-05-29 07:42 UTC, bluebill1049 commented
> Tell me if I'm wrong, but to my understanding, `control` is only being used inside `Controller` and not the `InnerComponent`, that's why we never passed it to `props` right?
> 
> For `name`, not all Components support `name` prop like `react-select`.
> 
> For `Controller`'s use case:
> 
> ```js-jsx
> <Controller
>   control={control}
>   name="reactSelect"
>   render={({ onChange, ...restProps }) => (
>     <Select
>       {...restProps}
>       onChange={onChange(selected => selected)}
>       options={options}
>     />
>   )}
> />
> ```

Yes correct, control, and name is for RHF.

2020-05-29 07:49 UTC, bluebill1049 commented
I think either:

1. `renderProps` all the way or (unless someone can solve my problem above)
2. `support` both separately. 

let's see the votes tmr.

2020-05-29 07:52 UTC, JeromeDeLeon commented
> ok running into the same problem again...
> 
> <img alt="Screen Shot 2020-05-29 at 5 28 17 pm" width="583" src="https://user-images.githubusercontent.com/10513364/83233279-d27f0d00-a1d1-11ea-8432-5133765a3916.png">
> 
> <img alt="Screen Shot 2020-05-29 at 5 28 09 pm" width="591" src="https://user-images.githubusercontent.com/10513364/83233289-d579fd80-a1d1-11ea-8e2e-40f1ddc0468b.png">
> 
> we still need to differentiate callback (as a component with payloads) vs react component in order to let the type work correctly, back to square one.

What file did you encounter this one? 
![Screenshot from 2020-05-29 15-49-04](https://user-images.githubusercontent.com/32805276/83235379-5b8f4780-a1c4-11ea-96ba-b83909b17480.jpg)

2020-05-29 07:55 UTC, bluebill1049 commented
> > ok running into the same problem again...
> > <img alt="Screen Shot 2020-05-29 at 5 28 17 pm" width="583" src="https://user-images.githubusercontent.com/10513364/83233279-d27f0d00-a1d1-11ea-8432-5133765a3916.png">
> > <img alt="Screen Shot 2020-05-29 at 5 28 09 pm" width="591" src="https://user-images.githubusercontent.com/10513364/83233289-d579fd80-a1d1-11ea-8e2e-40f1ddc0468b.png">
> > we still need to differentiate callback (as a component with payloads) vs react component in order to let the type work correctly, back to square one.
> 
> What file did you encounter that one?
> ![Screenshot from 2020-05-29 15-49-04](https://user-images.githubusercontent.com/32805276/83235379-5b8f4780-a1c4-11ea-96ba-b83909b17480.jpg)

update render type to

```
render:
    | ((data: {
        onChange: {
          (...event: any[]): void;
          (callback: (...args: any[]) => any): (...event: any[]) => void;
        };
        onBlur: () => void;
        value: any;
      }) => React.ReactElement)
    | React.ComponentType<any>;
```
then you will see the error in test file with controller.

2020-05-29 08:17 UTC, JeromeDeLeon commented
That's problematic. Couldn't we just support `render={Input}` and `render={props => <Input {...props} />}`?

2020-05-29 08:40 UTC, bluebill1049 commented
> That's problematic. Couldn't we just support `render={Input}` and `render={props => <Input {...props} />}`?

That's what I try to achieve here. :(

2020-05-29 08:47 UTC, JeromeDeLeon commented
Any reason why you need `React.ComponentType<any>`?

2020-05-29 08:49 UTC, bluebill1049 commented
> Any reason why you need `React.ComponentType<any>`?

for this `render={Checkbox}`.

2020-05-29 12:10 UTC, bluebill1049 commented
upon some investigation `render={Test}` || `render={() => {}}`is not a good pattern to follow and TS is not going to sing happily as well.

1. `render` prop all the way
2. `render` && `as` (similar as  react-router)

will decide that tmr and move on with this API.

2020-05-29 12:16 UTC, bluebill1049 commented
also worth mentioning if we going `render` prop only, for API consistency then make sense to remove `ErrorMessage` from this lib, because `as` props should be gone as well.

1. lose some package weight
2. the component is becoming too verbose anyhow

`<ErrorMessage render={({ message }) => <p>{messge}</p>} name="test" errors={errors} />`

vs

`errors.test?.messaga`

it's almost pointless to have such a component.

2020-05-29 12:18 UTC, kotarella1110 commented
> ok running into the same problem again...
> 
> <img alt="Screen Shot 2020-05-29 at 5 28 17 pm" width="583" src="https://user-images.githubusercontent.com/10513364/83233279-d27f0d00-a1d1-11ea-8432-5133765a3916.png">
> 
> <img alt="Screen Shot 2020-05-29 at 5 28 09 pm" width="591" src="https://user-images.githubusercontent.com/10513364/83233289-d579fd80-a1d1-11ea-8e2e-40f1ddc0468b.png">
> 
> we still need to differentiate callback (as a component with payloads) vs react component in order to let the type work correctly, back to square one.

I will look into whether I can.

2020-05-29 12:19 UTC, bluebill1049 commented
> > ok running into the same problem again...
> > <img alt="Screen Shot 2020-05-29 at 5 28 17 pm" width="583" src="https://user-images.githubusercontent.com/10513364/83233279-d27f0d00-a1d1-11ea-8432-5133765a3916.png">
> > <img alt="Screen Shot 2020-05-29 at 5 28 09 pm" width="591" src="https://user-images.githubusercontent.com/10513364/83233289-d579fd80-a1d1-11ea-8e2e-40f1ddc0468b.png">
> > we still need to differentiate callback (as a component with payloads) vs react component in order to let the type work correctly, back to square one.
> 
> I will look into whether I can.

Thanks @kotarella1110 enjoy your Friday, let's not spending more effort on this until tmr.

2020-05-29 12:37 UTC, JeromeDeLeon commented
I don't know Controller's solution. I looked at how `react-router` implemented their own types and seemed like they separated it with `component` and `render`. I could only passed the function component but when passing Class component, I couldn't. I'll let  @kotarella1110 or @stramel handle this. :laughing:

2020-05-29 12:38 UTC, bluebill1049 commented
> I don't know Controller's solution. I looked at how `react-router` implemented their own types and seemed like they separated it with `component` and `render`. I could only passed the function component but when passing Class component, I couldn't. I'll let @kotarella1110 or @stramel handle this. 😆

That's basically `as` and `render`.

2020-05-29 13:13 UTC, stramel commented
@bluebill1049 You should only need `React.ComponentType<{ value: any; onBlur: () => void; onChange: (...args: any[]) => void; }>`. That should support both `TextFields` and `(props) => <TextFields {...props} />`

2020-05-29 13:18 UTC, bluebill1049 commented
> @bluebill1049 You should only need
> 
> ```tsx
> React.ComponentType<{ value: any; onBlur: () => void; onChange: (...args: any[]) => void; }>
> ```
> 
> That should support both `TextFields` and `(props) => <TextFields {...props} />`

Thanks! make sense, will give it a go tmr morning.

2020-05-29 13:21 UTC, JeromeDeLeon commented
Is that so? I tried it out earlier with ComponentType but having a problem with 

```tsx
class Component extends Component<ControllerRenderProps, any> { }
```

2020-05-29 15:20 UTC, stramel commented
@JeromeDeLeon I modified your CodeSandbox from earlier, everything seems to be working for me. https://codesandbox.io/s/funny-nightingale-xpvuy?file=/src/App.tsx

2020-05-29 23:15 UTC, bluebill1049 commented
<img width="1006" alt="Screen Shot 2020-05-30 at 9 14 29 am" src="https://user-images.githubusercontent.com/10513364/83312545-fd12a980-a255-11ea-8efb-190fd2420f47.png">

let's not worry about `ComponentType` with render props, keep it as pure render props. let's see the vote result and decided what I suggest above for next.

2020-05-29 23:45 UTC, stramel commented
The problem there is you're not converting the props. Your Checkbox component doesn't take whatever you specified.

2020-05-30 00:07 UTC, bluebill1049 commented
> The problem there is you're not converting the props. Your Checkbox component doesn't take whatever you specified.

```
<Controller
  render={TextField}
  name="TextField"
  control={control}
  rules={{ required: true }}
/>
```

MUI TextField accepts `onChange, onBlur, value`, but still cry with TS. I think this proof is better to keep render props as just render props.

<img width="999" alt="Screen Shot 2020-05-30 at 10 06 36 am" src="https://user-images.githubusercontent.com/10513364/83314337-431f3b80-a25d-11ea-9ccc-7abeb3a0b0f1.png">

2020-05-30 00:08 UTC, bluebill1049 commented
I am getting renderProp only pass the automation, and then prepare for the next step.

2020-05-30 00:24 UTC, stramel commented
It's just a typing issue with conflicting onBlur props

2020-05-30 00:27 UTC, bluebill1049 commented
> It's just a typing issue with conflicting onBlur props

Yes, it's not compatible with `onBlur` but we probably going to have more issues like this with other libs? that's why I think keeping it as render props is actually easier right?

2020-05-30 00:28 UTC, bluebill1049 commented
> It's just a typing issue with conflicting onBlur props

FYI: I am updating all the automation app to render props for now.

2020-05-30 00:48 UTC, bluebill1049 commented
currently investigating an issue with Controller render props with useFieldArrya, somehow input lost focus... feel like mount and remount.

2020-05-30 00:55 UTC, bluebill1049 commented
![Screen Recording 2020-05-30 at 10 46 28 am](https://user-images.githubusercontent.com/10513364/83315549-fc810f80-a263-11ea-84e0-f20b157de83d.gif)

2020-05-30 02:07 UTC, bluebill1049 commented
@kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?

2020-05-30 07:47 UTC, bluebill1049 commented
<img width="601" alt="Screen Shot 2020-05-30 at 5 46 53 pm" src="https://user-images.githubusercontent.com/10513364/83322741-90bb9880-a29d-11ea-91f9-06a81d500034.png">

2020-05-30 09:42 UTC, kotarella1110 commented
> @kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?

I will do this tomorrow.

2020-05-30 09:46 UTC, kotarella1110 commented on src/controller.tsx
> +    onBlur,
Do you think that we can avoid unnecessary rendering with useCallback memo?

2020-05-30 09:51 UTC, bluebill1049 commented
> > @kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?
> 
> I will do this tomorrow.

nvm, I already did :) hehe just a small comment.

2020-05-30 09:51 UTC, bluebill1049 commented on src/controller.tsx
> +    onBlur,
🤔 hmmm good point.

2020-05-30 09:56 UTC, kotarella1110 commented
> > > @kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?
> > 
> > 
> > I will do this tomorrow.
> 
> nvm, I already did :) hehe just a small comment.

Sorry...
Reply is slow on weekends because I need to take care of my child 👶

2020-05-30 09:59 UTC, bluebill1049 commented
> > > > @kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?
> > > 
> > > 
> > > I will do this tomorrow.
> > 
> > 
> > nvm, I already did :) hehe just a small comment.
> 
> Sorry...
> Reply is slow on weekends because I need to take care of my child 👶

aha no worries @kotarella1110 didn't know you are a daddy! hahaha, take care little Kotaro. ❤️

2020-05-30 10:03 UTC, kotarella1110 commented
> > > > > @kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?
> > > > 
> > > > 
> > > > I will do this tomorrow.
> > > 
> > > 
> > > nvm, I already did :) hehe just a small comment.
> > 
> > 
> > Sorry...
> > Reply is slow on weekends because I need to take care of my child 👶
> 
> aha no worries @kotarella1110 didn't know you are a daddy! hahaha, take care little Kotaro. ❤️

hahaha I'm a daddy. My child was born when I joined the React Hook Form 💚

2020-05-30 10:09 UTC, JeromeDeLeon commented
Wow! That was great! Congratulations!! :confetti_ball:

2020-05-30 10:11 UTC, kotarella1110 commented
Thank you very much @JeromeDeLeon 💚

2020-05-30 10:12 UTC, bluebill1049 commented
> > > > > > @kotarella1110 can you please update your ErrorMessage component from 'children' to 'render' as well?
> > > > > 
> > > > > 
> > > > > I will do this tomorrow.
> > > > 
> > > > 
> > > > nvm, I already did :) hehe just a small comment.
> > > 
> > > 
> > > Sorry...
> > > Reply is slow on weekends because I need to take care of my child 👶
> > 
> > 
> > aha no worries @kotarella1110 didn't know you are a daddy! hahaha, take care little Kotaro. ❤️
> 
> hahaha I'm a daddy. My baby was born when I joined React Hook Form team 💚

Congrats! happy daddy! 👨‍👩‍👦

2020-05-30 10:17 UTC, kotarella1110 commented
Thanks @bluebill1049 💚 
I raise babies (My Baby and RHF) with care 👨‍👧

2020-05-30 10:22 UTC, bluebill1049 commented
> Thanks @bluebill1049 💚
> I raise babies (My Baby and RHF) with care 👨‍👧

hahaha sounds funny 4 dads... (1 dad left, he is a good dad as well, his name is Barry) RHF is like a little baby, it's growing each day with our cares!

2020-05-31 02:13 UTC, bluebill1049 commented on src/controller.tsx
> +    onBlur,
I did try `useCallback`, but it caught issue during automation test... and I didn't investigate further, feel free to take a look if you have time.

2020-05-31 07:00 UTC, JeromeDeLeon commented on cypress/integration/controller.ts
> +    cy.get('.container > p').should('have.length', 6);
The reason why it failed before was because we're getting all P tags. To solve that, get only the P tags under `.container`.

2020-05-31 07:02 UTC, JeromeDeLeon commented on src/controller.tsx
> +  const handlerProps = {
I hoisted it above to avoid `conditional memoizing` rule of hooks.

2020-05-31 07:03 UTC, JeromeDeLeon commented on cypress/integration/controller.ts
>    it('should validate the form with onBlur mode and reset the form', () => {
Here's a sample of test name where `reset` button didn't get called even though it was mentioned.

2020-05-31 07:10 UTC, bluebill1049 commented on cypress/integration/controller.ts
> +    cy.get('.container > p').should('have.length', 6);
awesome stuff @JeromeDeLeon thank you

2020-05-31 07:10 UTC, bluebill1049 commented on cypress/integration/controller.ts
>    it('should validate the form with onBlur mode and reset the form', () => {
thanks @JeromeDeLeon

2020-05-31 07:31 UTC, JeromeDeLeon commented on cypress/integration/controller.ts
>    it('should validate the form with onBlur mode and reset the form', () => {
I will patch it together with providing types for `cy` for code review. :smile:

2020-05-31 14:19 UTC, kotarella1110 commented on src/controller.tsx
> +  ): (...event: any[]) => void;
I have improved it possible to customize the return value to match the existing API, but this may not be necessary for render props.
I think we can remove it to keep the API simple, what do you think?

```ts
<Controller 
  render={({ onChange, ...props }) => (
    <CustomInput
      {...props}
      onChange={(e) => {
        const customValue = custom(e.target.value);
        onChange(customValue);
      }}
    />
  )}
  control={control} 
  name="test"  
/>
```

2020-05-31 22:50 UTC, bluebill1049 commented on src/controller.tsx
> +  ): (...event: any[]) => void;
sounds great.

2020-05-31 23:16 UTC, bluebill1049 commented on src/controller.tsx
> +  ): (...event: any[]) => void;
done.

2020-05-31 23:21 UTC, bluebill1049 commented on src/controller.tsx
> +  ): (...event: any[]) => void;
Do you want to do a commit on this one? I think i stuff it up by removing that overload function.

2020-05-31 23:56 UTC, kotarella1110 commented on src/controller.tsx
> +  ): (...event: any[]) => void;
@bluebill1049 yes. I will fix soon!

2020-05-31 23:57 UTC, bluebill1049 commented on src/controller.tsx
> +  ): (...event: any[]) => void;
ty

2020-06-01 01:36 UTC, merged