remove unnecessary `deps` in `useForm` hook
react-hook-form/react-hook-form pull request #2047
Opened 2020-07-03 12:15 UTC by MHA15

this PR will remove refs in dependency list of `useCallback` and also will move some static variables out of hook body to not need to add them to dependency list 

** NOTE: isWindowUndefined and isWeb and isProxyEnabled are static(constant) variables and can not be changed after first run of js file on same engine **

2020-07-03 12:35 UTC, bluebill1049 commented on src/useForm.ts
> +const isProxyEnabled = isWeb ? 'Proxy' in window : typeof Proxy !== UNDEFINED;
Thanks for this PR, have we consider in SSR?

2020-07-03 12:43 UTC, MHA15 commented on src/useForm.ts
> +const isProxyEnabled = isWeb ? 'Proxy' in window : typeof Proxy !== UNDEFINED;
also in SSR when this file run for the first time it will calculate these variables and will never changed 
in client side again this file will be run and will calculate these variables for it self

2020-07-03 12:55 UTC, bluebill1049 commented on src/useForm.ts
> +  const optionsRef = React.useRef<typeof options>({} as typeof options);
This actually increase the package size, let's keep them flat, please.

2020-07-03 14:12 UTC, MHA15 commented on src/useForm.ts
> +  const optionsRef = React.useRef<typeof options>({} as typeof options);
increase package size? are you sure? I think this will decrease it (because of using less useRef )
let's not talk about package size in this one , It's difference might be 1KB or less in development mode, and also as I said before using less hooks are more important

I will change these in next version (createControl function) and will remove all refs (don't worry about it)

2020-07-03 16:02 UTC, keiya01 commented on src/useForm.ts
> +  const optionsRef = React.useRef<typeof options>({} as typeof options);
I actually saw increasing file size.
I think you should remove only unnecessary `deps` because bundling `options` increase bundle size.

2020-07-03 17:17 UTC, MHA15 commented on src/useForm.ts
> +  const optionsRef = React.useRef<typeof options>({} as typeof options);
thanks for your attention
I had run `yarn bundlesize` and I got 8.42KB in my branch and 8.41KB on master? am I true?
are we talking about 10B difference? :)

2020-07-03 23:05 UTC, bluebill1049 commented on src/useForm.ts
> +  const optionsRef = React.useRef<typeof options>({} as typeof options);
yes, correct. sorry, every B counts here.

2020-07-03 23:15 UTC, bluebill1049 commented on src/useForm.ts
> +  const optionsRef = React.useRef<typeof options>({} as typeof options);
> I will change these in next version (createControl function) and will remove all refs.

Thanks, I am looking forward to that.

2020-07-04 03:42 UTC, JeromeDeLeon requested changes
I do appreciate your work about using `optionsRef` instead of spreading them but we do value bundle size so much like what @bluebill1049 and @keiya01 told you. Thanks again! we value your contribution to the enhancement of this library.

2020-07-04 03:42 UTC, JeromeDeLeon commented on src/useForm.ts
> +const isProxyEnabled = isWeb ? 'Proxy' in window : typeof Proxy !== UNDEFINED;
Couldn't we move this to `utils` folder? If every function is hoisted out of the lib, please move it to respective folder. That way we could keep the main file clean as much as possible. Thank you. Nice work! :smile:

2020-07-04 05:44 UTC, MHA15 commented on src/useForm.ts
> +  const optionsRef = React.useRef<typeof options>({} as typeof options);
third commit has been removed from PR

2020-07-04 05:46 UTC, MHA15 commented on src/useForm.ts
> +const isProxyEnabled = isWeb ? 'Proxy' in window : typeof Proxy !== UNDEFINED;
yes I do want it too, but I didn't find any related file in utils and I didn't know where should I put them, can you help me and tell which file I should put them?

2020-07-04 07:33 UTC, bluebill1049 commented
Thanks @MHA15

2020-07-04 07:33 UTC, merged

2020-07-04 07:34 UTC, bluebill1049 commented on src/useForm.ts
> +const isProxyEnabled = isWeb ? 'Proxy' in window : typeof Proxy !== UNDEFINED;
no worries @MHA15 i will take it over and sort it out 👍 get your contribution in first 🥳

2020-07-04 08:31 UTC, MHA15 commented
> Thanks @MHA15
that is my pleasure to participate on this awesome library