Allow OnSubmit event handler to return promises
react-hook-form/react-hook-form pull request #218
Opened 2019-08-15 08:44 UTC by bmamouri

Simple change to allow async event handlers in type definitions

2019-08-15 09:00 UTC, bluebill1049 commented
Thanks for the PR @bmamouri looks like this change break the build (automation).

<img width="972" alt="Screen Shot 2019-08-15 at 6 59 50 pm" src="https://user-images.githubusercontent.com/10513364/63084595-e59c5580-bf8e-11e9-868f-4e7111018589.png">

2019-08-15 09:27 UTC, bluebill1049 commented
probably should be void | Promise<void>

2019-08-15 12:23 UTC, stramel requested changes

2019-08-15 12:23 UTC, stramel commented on src/types.ts
> +) => Promise<void>;
`void | Promise<void>`

2019-08-15 12:28 UTC, bluebill1049 commented
@stramel those automation tests is pretty useful here 😺

2019-08-15 22:11 UTC, stramel commented on src/types.ts
> +) => Promise<void>;
@bmamouri You should be able to just accept this suggested change now :)

2019-08-16 02:34 UTC, bluebill1049 commented
@bmamouri can you please accept the change and we can merge it in :)?

2019-08-16 10:51 UTC, bmamouri commented
@bluebill1049, Great library mate! Good to see that you are from Sydney too.

@stramel, Thanks for the fix

2019-08-16 11:00 UTC, bluebill1049 approved these changes

2019-08-16 11:01 UTC, merged

2019-08-16 11:01 UTC, bluebill1049 commented
thanks mate @bmamouri and your contribution ❤️