fix getMultipleSelectValue for HTMLOptionsCollection
react-hook-form/react-hook-form pull request #229
Opened 2019-08-19 16:04 UTC by tizz98

I've been getting the following error when using this library with `react-bootstrap` (https://react-bootstrap.github.io/)

```
options.filter is not a function
```

This is because the ref being passed to `register` is actually `HTMLOptionsCollection` not `HTMLOptionElement[]`. I fixed this temporarily by hacking `HTMLOptionsCollection` but it would be nice not to have to do that.

2019-08-19 21:35 UTC, bluebill1049 requested changes

2019-08-19 21:35 UTC, bluebill1049 commented on src/logic/getMultipleSelectValue.ts
> +const filterOptions = (options: HTMLOptionElement[]): string[] =>
export default (options: HTMLOptionElement[] | HTMLOptionsCollection): string[] =>	const filterOptions = (options: HTMLOptionElement[]): string[] =>
  [...options].filter(({ selected }): boolean => selected).map(({ value }): string => value);

2019-08-19 21:35 UTC, bluebill1049 commented
thanks very much for the PR ❤️

2019-08-19 21:36 UTC, bluebill1049 commented on src/logic/getMultipleSelectValue.ts
> +const filterOptions = (options: HTMLOptionElement[]): string[] =>
I think we can simplify the above to what I suggested :)

2019-08-19 23:29 UTC, stramel commented on src/logic/getMultipleSelectValue.ts
> +const filterOptions = (options: HTMLOptionElement[]): string[] =>
agreed

2019-08-20 06:50 UTC, bluebill1049 commented
thank you :)

2019-08-20 06:50 UTC, merged

2019-08-20 06:51 UTC, bluebill1049 commented
@tizz98 I will publish the patch tonight. if you need it now. you can use https://cdn.pika.dev/react-hook-form/master

2019-08-20 10:06 UTC, bluebill1049 commented
published :) https://github.com/react-hook-form/react-hook-form/releases/tag/v3.22.0