new feature onTouch mode
react-hook-form/react-hook-form pull request #2377
Opened 2020-07-27 07:47 UTC by bluebill1049

`onTouch` mode will only trigger validation after input gets touched.

2020-07-29 07:13 UTC, bluebill1049 commented
TS question: @kotarella1110 
if i change this line (https://github.com/react-hook-form/react-hook-form/pull/2377/files#diff-a922078008692a8cd2e441a97dd8fa24R96) to `Omit<xxx, 'all', 'onTouch'>` then i get an issue with `keyof mode` in `SkipValidation` function, do you know how to solve this problem?

2020-07-29 09:02 UTC, kotarella1110 commented
> TS question: @kotarella1110
> if i change this line (https://github.com/react-hook-form/react-hook-form/pull/2377/files#diff-a922078008692a8cd2e441a97dd8fa24R96) to `Omit<xxx, 'all', 'onTouch'>` then i get an issue with `keyof mode` in `SkipValidation` function, do you know how to solve this problem?

what line is that written on?

2020-07-29 09:05 UTC, bluebill1049 commented
oops that link didn't work...

`form.ts`
<img width="627" alt="Screen Shot 2020-07-29 at 7 05 04 pm" src="https://user-images.githubusercontent.com/10513364/88780496-6a977380-d1ce-11ea-8961-681c27c2e8ff.png">

2020-07-29 13:12 UTC, kotarella1110 commented
@bluebill1049 You should use `Exclude` instead of `Omit` 👍

2020-07-30 01:35 UTC, bluebill1049 commented
oh thanks @kotarella1110

2020-08-09 12:24 UTC, JeromeDeLeon commented on src/useForm.test.tsx
> +      });
Kinda confuse, will it trigger also even without doing blur event? because in my understanding, `onTouch` will validate the moment I focus/touch the field, right? and then again, you triggered the `onChange` function then validation run, but should it run? I'm kinda confuse with this behavior. I'm good with this feature just confuse sorry :sweat_smile:

2020-08-09 12:30 UTC, bluebill1049 commented on src/useForm.test.tsx
> +      });
good question :) touched only gets updated after user leave input focused. so the first focus with change will not trigger validation. only after they have focused on the inputs.

2020-08-09 12:30 UTC, bluebill1049 commented on src/useForm.test.tsx
> +      });
perhaps we should name it `onTouched`

2020-08-09 12:35 UTC, bluebill1049 commented on src/useForm.test.tsx
> +      });
make sense. updating...

2020-08-09 15:59 UTC, JeromeDeLeon commented on src/useForm.test.tsx
> +      });
Sorry I forgot to follow up. Thanks for your explanation. It somehow makes sense.

Shouldn't we have revalidate mode for this or blur is enough?

2020-08-09 23:05 UTC, bluebill1049 commented on src/useForm.test.tsx
> +      });
after input been touched, the validation will be switched to `onChange`. That's the difference.

2020-08-09 23:19 UTC, JeromeDeLeon commented on src/useForm.ts
> +      ref: (fieldsRef.current[name] || {})!.ref,
Maybe because of it's compiled version is longer hence causing more bytes? Am I right? @bluebill1049

2020-08-09 23:19 UTC, JeromeDeLeon commented on src/useForm.test.tsx
> +      });
Thank you 😁

2020-08-09 23:25 UTC, bluebill1049 commented on src/useForm.ts
> +      ref: (fieldsRef.current[name] || {})!.ref,
yes :( it will add a polyfill.

2020-08-09 23:27 UTC, bluebill1049 commented on src/useForm.test.tsx
> +      });
Some users/UX prefer this type of validation. Personally I prefer `onSubmt` but it's good to give them the option too, otherwise, they will have to dot the following:

```
useForm({ mode: 'onChange' })

{touched.test && errors.test.message}
```

2020-08-09 23:46 UTC, adhrinae commented on src/useForm.ts
> +      ref: (fieldsRef.current[name] || {})!.ref,
Understood 👍

2020-08-10 00:05 UTC, JeromeDeLeon commented on src/useForm.test.tsx
> +      });
Same haha I also prefer to handle validation onSubmit 🤣

2020-08-10 05:52 UTC, keiya01 requested changes
This is awesome feature 🎉

2020-08-10 05:52 UTC, keiya01 commented on src/useForm.test.tsx
> +      expect(screen.getByText('This is required.')).toBeInTheDocument();
```suggestion
      expect(screen.queryByText('This is required.')).toBeInTheDocument();
```

I think you should `screen.queryByText()` because `getBy*` method throw error when specified element could not found.

2020-08-10 05:52 UTC, keiya01 commented on src/useForm.test.tsx
> +      expect(screen.getByText('This is required.')).toBeInTheDocument();
```suggestion
      expect(screen.queryByText('This is required.')).toBeInTheDocument();
```

2020-08-10 06:12 UTC, bluebill1049 commented on src/useForm.test.tsx
> +      expect(screen.getByText('This is required.')).toBeInTheDocument();
awesome! thanks @keiya01 🙏

2020-08-11 01:50 UTC, pmaier983 approved these changes
LGTM! Awesome work :D

2020-08-11 01:54 UTC, bluebill1049 commented
Thanks for the review @keiya01 and @pmaier983. Will merge this in once all the remaining issues are resolved. we can release this with @adhrinae's feature too.

2020-08-14 08:17 UTC, merged