Feature/better error message
react-hook-form/react-hook-form pull request #2461
Opened 2020-08-03 06:53 UTC by bluebill1049

2020-08-03 07:29 UTC, bluebill1049 commented
@keiya01 i think we have a test case which fails sometimes :(
<img width="833" alt="Screen Shot 2020-08-03 at 5 28 57 pm" src="https://user-images.githubusercontent.com/10513364/89156865-d141d600-d5ae-11ea-8fc2-8243da0b3930.png">

2020-08-03 07:37 UTC, keiya01 commented
Maybe, this error is occurred by cache in jest. You can resolve this error by executing `yarn test --clearCache`.

2020-08-03 07:43 UTC, keiya01 requested changes
I reviewed this PR. And I sent commit. :)

2020-08-03 07:43 UTC, keiya01 commented on src/controller.tsx
> +    if (!control) {
```suggestion
    if (!control && !methods.control) {
```

2020-08-03 07:43 UTC, keiya01 commented on src/useFieldArray.ts
> +    if (!control) {
```suggestion
    if (!control && methods.control) {
```

2020-08-03 07:46 UTC, bluebill1049 commented
awesome! thanks @keiya01 good pick up, miss the context 🙏

2020-08-03 07:53 UTC, keiya01 commented
I fixed some code.

2020-08-03 07:57 UTC, keiya01 submitted a review, later dismissed
LGTM 🧙‍♂️

2020-08-03 07:59 UTC, bluebill1049 commented
thanks @keiya01

2020-08-03 08:01 UTC, keiya01 approved these changes

2020-08-03 08:01 UTC, merged

2020-09-06 21:57 UTC, gregfenton commented
I have code that was happily running in dev with 6.1.2.  Upgrading to 6.7.2 I now get these warnings about my Controller defaultValues being 'undefined'.  I set my defaultValues to the previously saved value (if any) for a given form.  If the form hasn't been saved previously, then the defaultValue is actually `undefined`.

Is there a doc update (or just hint me the answer here  ;) ) as to how to handle this situation?  What should defaultValue be set to when there isn't actually a default value?

Thanks in advance!

2020-09-06 22:50 UTC, bluebill1049 commented
> I have code that was happily running in dev with 6.1.2. Upgrading to 6.7.2 I now get these warnings about my Controller defaultValues being 'undefined'. I set my defaultValues to the previously saved value (if any) for a given form. If the form hasn't been saved previously, then the defaultValue is actually `undefined`.
> 
> Is there a doc update (or just hint me the answer here ;) ) as to how to handle this situation? What should defaultValue be set to when there isn't actually a default value?
> 
> Thanks in advance!

an empty string will do, undefined may lead to issue with Controller.

2020-09-07 17:41 UTC, gregfenton commented
I am using `<Controller>` throughout a complex, nested, and dynamically generated form.

Will the above approach work for fields that will otherwise contain non-string values?  In particular, the field that 6.7.2 is complaining about should either be empty (currently `undefined`) or will contain an object `{comment: theTextValue, photos: [...theUrlArray]}`.

So will setting that field to empty string (`''`) be okay for "no value" and set the object when there is a comment and/or values in the URL array?  Is there any other thing I should be thinking about when it comes to setting, unsetting and resetting fields within the form?

Thanks for the help (and your overall contributions!!)

2020-09-07 22:31 UTC, bluebill1049 commented
> I am using `<Controller>` throughout a complex, nested, and dynamically generated form.
> 
> Will the above approach work for fields that will otherwise contain non-string values? In particular, the field that 6.7.2 is complaining about should either be empty (currently `undefined`) or will contain an object `{comment: theTextValue, photos: [...theUrlArray]}`.
> 
> So will setting that field to empty string (`''`) be okay for "no value" and set the object when there is a comment and/or values in the URL array? Is there any other thing I should be thinking about when it comes to setting, unsetting and resetting fields within the form?
> 
> Thanks for the help (and your overall contributions!!)

as long as you can supply a `defaultValue` at Controller or useForm `defaultValues`, it should be fine. I mean it's not the end of world if you don't supply `defaultValue`, but it's definitely better practice and less issue later on.

2020-09-08 00:09 UTC, gregfenton commented
I read the descriptions of `defaultValue` (Controller and useForm), then the links to React's controlled & uncontrolled components...maybe it is just me but none of it jumps out saying "here is how `defaultValue` impacts the behaviour of the component/form/submission/etc.".  IMO it is up to the reader to wade through the various pages and APIs and build out the picture in their own minds.  Or is there one key "here is how it works" doc I am failing to absorb?

Questions I still have:

- when do defaultValue(s) get used - initial load, submission (success/fail), form reset?
- does the `value` prop of a control/form actually get the `defaultValue`, or is defaultValue directly referenced when `value` is empty/null/undefined?

2020-09-08 00:16 UTC, bluebill1049 commented
> I read the descriptions of `defaultValue` (Controller and useForm), then the links to React's controlled & uncontrolled components...maybe it is just me but none of it jumps out saying "here is how `defaultValue` impacts the behaviour of the component/form/submission/etc.". IMO it is up to the reader to wade through the various pages and APIs and build out the picture in their own minds. Or is there one key "here is how it works" doc I am failing to absorb?
> 
> Questions I still have:
> 
> * when do defaultValue(s) get used - initial load, submission (success/fail), form reset?
> * does the `value` prop of a control/form actually get the `defaultValue`, or is defaultValue directly referenced when `value` is empty/null/undefined?

1. like I suggested above follow the rule to provide `defaultValue` (none undefined) which why the warning is in the first place.
2. have a look at the source code, which may give you better idea: https://github.com/react-hook-form/react-hook-form/blob/master/src/controller.tsx#L57
3. `defaultValue` is for the initial input value, just like `<input defaultValue="test" />`
4. > maybe it is just me but none of it jumps out saying "here is how defaultValue impacts the behaviour of the component/form/submission/etc."
it's open-source, you can contribute and help too.

2020-09-08 01:13 UTC, gregfenton commented
Happy to do so and will.  Just wanted to be sure I wasn't missing something obvious.