Removes redundant dependencies in append and remove of useFieldArray
react-hook-form/react-hook-form pull request #2780
Opened 2020-08-31 13:26 UTC by michalbundyra

Fixes #2778

In `append` method `fillEmptyArray` cares just about the length of the array, so the `fields` dep was not needed there at all.

In `remove` dependency `fields` was not used.

All tests are still green. Probably we should add some test cases, so these dependencies are not re-added to the methods in `useFieldArray`.

2020-08-31 13:34 UTC, bluebill1049 commented on src/useFieldArray.ts
> +          fillEmptyArray(new Array(allFields.current.length)),
```suggestion
          fillEmptyArray(allFields.current),
```

hmm, honestly I am trying to move away with that ref object :(

2020-08-31 13:35 UTC, bluebill1049 commented on src/useFieldArray.ts
> +          fillEmptyArray(new Array(allFields.current.length)),
I am happy to get this PR over the line, but I can't guarantee future change by completely removing that ref object. 🙏

2020-08-31 13:36 UTC, bluebill1049 commented
hmmm actually I am going to hold this PR, I think to remove that ref object is the correct approach.

2020-08-31 13:36 UTC, michalbundyra commented on src/useFieldArray.ts
> +          fillEmptyArray(new Array(allFields.current.length)),
The thing that it is still used here anyway - line 256 (260). That works to eliminate `fields` dep.
If you have better solution I'd be happy to see it :)

2020-08-31 13:38 UTC, michalbundyra commented
@bluebill1049 

> hmmm actually I am going to hold this PR, I think to remove that ref object is the correct approach

Ok, I believe you will find a better way to eliminate this dependency, as it is not needed in `prepend` as well. Thanks.

2020-09-01 00:01 UTC, bluebill1049 commented on src/useFieldArray.ts
> +          fillEmptyArray(new Array(allFields.current.length)),
```suggestion
          fillEmptyArray(allFields.current),
```

2020-09-01 00:02 UTC, bluebill1049 commented on src/useFieldArray.ts
> +    remove: React.useCallback(remove, [name, errors]),
please fix remove as well with `ref`.

2020-09-01 00:02 UTC, bluebill1049 requested changes
Thanks for the PR.

2020-09-01 05:42 UTC, michalbundyra commented on src/useFieldArray.ts
> +    remove: React.useCallback(remove, [name, errors]),
It was not used, as you see all tests are still green. Unless I am missing something?

I am not sure also where `errors` dep is used in these functions? Maybe it can be removed as well?

2020-09-01 05:45 UTC, bluebill1049 commented on src/useFieldArray.ts
> +    remove: React.useCallback(remove, [name, errors]),
you are right, that was my bad!

2020-09-01 05:45 UTC, bluebill1049 commented
dame lint failed, you may have to pull the latest and run `yarn lint`. thanks

2020-09-01 05:50 UTC, michalbundyra commented on src/useFieldArray.ts
> +    remove: React.useCallback(remove, [name, errors]),
Do you want me to remove `errors` dep as well. then?

2020-09-01 05:50 UTC, michalbundyra commented
@bluebill1049 

> dame lint failed

Fixed! :)

2020-09-01 05:51 UTC, bluebill1049 commented on src/useFieldArray.ts
> +    remove: React.useCallback(remove, [name, errors]),
it's used in `batchStateUpdate`.

2020-09-01 05:53 UTC, bluebill1049 commented on src/useFieldArray.ts
> +    remove: React.useCallback(remove, [name, errors]),
I will clean this update to only have `name` as dep. you can leave that to me, will sort out tonight.

2020-09-01 05:56 UTC, merged