Improve/types
react-hook-form/react-hook-form pull request #303
Opened 2019-09-10 01:15 UTC by bluebill1049

2019-09-10 01:38 UTC, bluebill1049 commented
Feel free to apply suggestions :)

2019-09-10 11:15 UTC, bluebill1049 commented on src/useForm.ts
> +      // @ts-ignore
I couldn't find a way to not having ts-ignore here, help is much appreciated :)

2019-09-10 11:22 UTC, barrymay commented on src/contextTypes.ts
> +  watch(field: Name | string, defaultValue?: string): any | void;
why the any change? (where we need an any it would be good to explain why in a comment if possible)

2019-09-10 11:36 UTC, barrymay submitted a review, later dismissed
Overall seems like a step in the right direction.  You can put a beta release out and we can check it.  
My major concern is it seems we're adding more 'as' cases than removing them.

2019-09-10 11:36 UTC, barrymay commented on src/contextTypes.ts
> +  reset: () => void;
not a blocker, but a VoidFunction is a TS-defined alias for () => void so it is the same thing ;)

2019-09-10 11:36 UTC, barrymay commented on src/logic/getDefaultValue.ts
> +export default <Data extends any, FieldName extends keyof Data = keyof Data>(
I appreciate that FieldValue was an any so it did the same thing, but having that name gave it a semantic meaning (I'm fine to be overruled here ;) )

2019-09-10 11:36 UTC, barrymay commented on src/types.ts
> +export interface Error {
I would just be careful here for high level name collision with a JS Error

2019-09-10 11:41 UTC, bluebill1049 commented on src/types.ts
> +export interface Error {
yes, you are right thanks @barrymay

2019-09-10 11:45 UTC, bluebill1049 commented on src/contextTypes.ts
> +  watch(field: Name | string, defaultValue?: string): any | void;
I think I will revert this back like you suggested it's more semantic as FieldValue.

2019-09-10 11:48 UTC, bluebill1049 commented
@barrymay is it better to leave more ts-ignore?

2019-09-10 12:00 UTC, bluebill1049 commented
`3.23.6-beta.1` please help on testing with this beta ❤️

2019-09-10 13:28 UTC, barrymay commented
> @barrymay is it better to leave more ts-ignore? (for some of the `as`)

If it's leaving it to "as any" to make it work, then I would say yes.  There are some valid cases for as, but leaving the ts-ignore says "this is not great, we should come back to try to work it out)

2019-09-10 21:41 UTC, bluebill1049 commented
thanks @barrymay i will update accordingly

2019-09-11 00:33 UTC, bluebill1049 commented
`3.23.6-beta.2`

2019-09-11 03:37 UTC, barrymay commented on src/types.ts
> -export type Validate = (data: FieldValue) => string | boolean | void;
there's a problem with this (based on my testing of the beta).  Previously my code worked fine with the below code (taking inputs, giving string outputs), but in the new code this isn't allowed.   Any idea why?

```
validate: (inputValue: string[]) => {
          if (!inputValue || !Array.isArray(inputValue)) {
            return 'Invalid result from player list';
          }
          if (!inputValue.length) {
            return 'At least one player must be selected';
          } else if (inputValue.length > 4) {
            return 'Only 4 players are allowed';
          }
          return '';
```

2019-09-11 03:38 UTC, barrymay requested changes
See my error - I don't think this change can go forward, we need to ensure the validation functions continue to work as expected.  Were we expecting a breaking change?

2019-09-11 04:03 UTC, bluebill1049 commented
no we shouldn't expect a breaking changing. I am investigating why

2019-09-11 04:04 UTC, bluebill1049 commented on src/types.ts
> -export type Validate = (data: FieldValue) => string | boolean | void;
this was moved to line 58, so it's not been deleted or changed. I am looking into why

2019-09-11 04:12 UTC, bluebill1049 commented on src/types.ts
> -export type Validate = (data: FieldValue) => string | boolean | void;
dame! find the issue `FieldValue` thanks heaps @barrymay

2019-09-11 04:14 UTC, bluebill1049 commented
going to add an automation check for this usage too, so it will report that issue earlier

2019-09-11 13:38 UTC, barrymay submitted a review, later dismissed
I tested with 3.23.6-beta.3, looks good to go from my test!

2019-09-11 23:30 UTC, bluebill1049 commented
@stramel if you got sometime please take a review on this 🙏, if you are busy then I will merge this at the end of the day.

2019-09-12 03:29 UTC, stramel commented
If you modify the FieldName to extend a string you won't have to do FieldName | string.

2019-09-12 03:34 UTC, stramel commented on src/useForm.ts
> +  FieldName extends keyof FormValues = keyof FormValues,
This will need changed to `FieldName extends Extract<keyof FormValues, string> = Extract<keyof FormValues, string>,` in order for it to be assignable to strings

2019-09-12 03:35 UTC, stramel commented
Lots of casts in here :/

2019-09-12 04:53 UTC, bluebill1049 commented
@stramel we can improve on the next PR with your help ❤️

2019-09-12 04:54 UTC, bluebill1049 commented on src/useForm.ts
> +  FieldName extends keyof FormValues = keyof FormValues,
hmmm more complicated typescript for me hehe

2019-09-12 06:36 UTC, merged