Feature/array of checkboxes
react-hook-form/react-hook-form pull request #500
Opened 2019-11-13 23:51 UTC by ldanet

Adds support for groups of checkboxes as a single field as in the first example there:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Using_checkbox_inputs

2019-11-13 23:53 UTC, ldanet commented
I tried to not have breaking changes and have single checkboxes behave the same as they already do.

2019-11-14 00:03 UTC, bluebill1049 commented
looks like two automation test suits failed.

2019-11-14 00:17 UTC, bluebill1049 commented on src/useForm.ts
> +      } else if (isCheckBoxInput(type) && options) {
The tricky part is when options get populated, for the `radio` button. you can assume options will always be there. That why I was suggesting to use PHP like syntax to indicate that this checkbox is actually an array.

`<input name="test[]" />`

2019-11-14 01:08 UTC, ldanet commented on src/useForm.ts
> +      } else if (isCheckBoxInput(type) && options) {
the `&& options` here is just to make Typescript happy. Since the checkbox is registered the same as the radio, it shares the same assumptions most of the code, apart from the places where you get the value. 
This line of code reflects the code for the radio input a few lines above:
```ts
if (isRadioInput(type) && options) {
  options.forEach(
     ({ ref: radioRef }) => (radioRef.checked = radioRef.value === value),
   );
);
```

2019-11-14 01:10 UTC, ldanet commented
> looks like two automation test suits failed.

I forgot to update the cypress tests! Doing that.

2019-11-14 01:11 UTC, bluebill1049 commented
> > looks like two automation test suits failed.
> 
> I forgot to update the cypress tests! Doing that.

awesome :) thanks

2019-11-14 01:12 UTC, bluebill1049 commented on src/useForm.ts
> +      } else if (isCheckBoxInput(type) && options) {
oh I see, I haven't looked it close enough :) I will take a look and help to test as well.

2019-11-14 02:09 UTC, bluebill1049 commented on src/logic/findRemovedFieldAndRemoveListener.test.ts
> +  it('should work for checkbox type input', () => {
```suggestion

  it('should work for checkbox type input', () => {
```

2019-11-14 02:10 UTC, bluebill1049 commented on src/logic/getCheckboxValue.test.ts
> +  it('should return values for checked boxes only', () => {
```suggestion

  it('should return values for checked boxes only', () => {
```

2019-11-14 02:10 UTC, bluebill1049 commented on src/logic/getCheckboxValue.test.ts
> +  it('should return empty array for multi checkbox with no checked box', () => {
```suggestion

  it('should return empty array for multi checkbox with no checked box', () => {
```

2019-11-14 02:11 UTC, bluebill1049 commented on src/logic/getCheckboxValue.ts
> +import { RadioOrCheckboxOption } from '../types';
minor: could you please move type to the bottom of the `import`? (consistency)

2019-11-14 02:12 UTC, bluebill1049 commented on src/logic/getCheckboxValue.ts
> +import { isUndefined } from 'util';
```suggestion
import isUndefined from '../utils/isUndefined';
```

2019-11-14 02:13 UTC, bluebill1049 commented on src/logic/getCheckboxValue.ts
> +    if (options.length > 1) {
```suggestion
    if (options.length) {
```

2019-11-14 02:15 UTC, bluebill1049 commented on src/logic/getCheckboxValue.ts
> +      if (options[0].ref.checked) {
`const { checked, value } = options[0].ref;`

2019-11-14 02:16 UTC, bluebill1049 commented on src/logic/getCheckboxValue.ts
> +};
This is really smart! @ldanet your solution is great. ❤️

2019-11-14 02:16 UTC, bluebill1049 commented on src/logic/getFieldValue.test.ts
> +  it('should return false when checkbox input value is not found', () => {
```suggestion

  it('should return false when checkbox input value is not found', () => {
```

2019-11-14 02:16 UTC, bluebill1049 commented on src/logic/getFieldValue.test.ts
> +    ).toEqual(false);
```suggestion
    ).toBeFalsy();
```

2019-11-14 02:17 UTC, bluebill1049 commented on src/logic/getFieldValue.test.ts
> +          type: 'file',
Great pick up! thank you

2019-11-14 02:19 UTC, bluebill1049 commented on src/useForm.test.tsx
> +    it('should set value of multiple checkbox input correctly', async () => {
```suggestion

    it('should set value of multiple checkbox input correctly', async () => {
```

2019-11-14 02:29 UTC, bluebill1049 requested changes
All minor comments :) really great stuff here. Thanks for your solution, it is a lot better than mine.

2019-11-14 02:29 UTC, bluebill1049 commented on src/useForm.ts
> +        options.length > 1
```suggestion
        options.length
```

2019-11-14 02:29 UTC, bluebill1049 commented on src/useForm.ts
> +      isRadio || isCheckBox
maybe we can change this into a variable?

2019-11-14 02:29 UTC, bluebill1049 commented on src/logic/__snapshots__/findRemovedFieldAndRemoveListener.test.ts.snap
> +exports[`findMissDomAndClean should work for checkbox type input 1`] = `undefined`;
hmmm, this is for me to fix, looks like those unit tests r unless...

2019-11-14 02:29 UTC, bluebill1049 commented on src/logic/getCheckboxValue.test.ts
> +import getCheckboxValue from './getCheckboxValue';
nice unit test :)

2019-11-14 02:29 UTC, bluebill1049 commented on src/logic/getCheckboxValue.ts
> +      return { value: false, isValid: false };
```suggestion
      return defaultResult;
```

2019-11-14 02:29 UTC, bluebill1049 commented on src/logic/getFieldValue.test.ts
> +  it('should return the correct value when type is checkbox', () => {
```suggestion

  it('should return the correct value when type is checkbox', () => {
```

2019-11-14 02:29 UTC, bluebill1049 commented on src/logic/getFieldValue.ts
> +    return field ? getCheckboxValue(field.options).value : false;
I think we can bring this logic inside `getCheckboxValue`

`return getCheckboxValue(fields[name]).value;`

2019-11-14 02:29 UTC, bluebill1049 commented on src/logic/validateField.ts
> +      ref: isRadio || isCheckBox ? fields[typedName].options[0].ref : ref,
maybe we can hoist it into a variable as well :)

2019-11-14 02:40 UTC, ldanet commented on src/logic/getCheckboxValue.ts
> +    if (options.length > 1) {
It's `> 1` not ` > 0`, we still need to compare :smile:

2019-11-14 02:47 UTC, bluebill1049 commented on src/logic/getCheckboxValue.ts
> +    if (options.length > 1) {
you are right!

2019-11-14 02:52 UTC, ldanet commented on src/useForm.ts
> +      isRadio || isCheckBox
Indeed they're never used alone now.

2019-11-14 02:53 UTC, ldanet commented on src/logic/getFieldValue.ts
> +    return field ? getCheckboxValue(field.options).value : false;
The issue is that if `fields[name]` is undefined (and Typescript has no reason to think it couldn't be), then trying to access `fields[name].options` is an error.

2019-11-14 02:54 UTC, bluebill1049 commented on src/logic/getFieldValue.ts
> +    return field ? getCheckboxValue(field.options).value : false;
that's fine :) i will remove the suggestion.

2019-11-14 03:02 UTC, bluebill1049 approved these changes
THANK YOU!

2019-11-14 03:03 UTC, merged

2019-11-14 03:14 UTC, JeromeDeLeon commented on src/logic/getCheckboxValue.ts
> +    if (options.length > 1) {
What about `options[1]` ?

2019-11-14 03:16 UTC, bluebill1049 commented on src/logic/getCheckboxValue.ts
> +    if (options.length > 1) {
yeah! love it less code the better :)