Update package.json exports rule to allow importing specific file
react-hook-form/react-hook-form pull request #8127
Opened 2022-04-02 22:28 UTC by smeng9

When building our code using react-hook-form as an external library, some are shipped using esm and some are using cjs, which causes useFormContext to return null. See https://github.com/react-hook-form/react-hook-form/discussions/3894

In one of the replies https://github.com/react-hook-form/react-hook-form/discussions/3894#discussioncomment-2135181 it mentioned the cause is due to the mixed usage of esm and cjs.

Currently the import esm or cjs module is automatically determined and the system may not be very smart. It always causes some problem.

This pull request changes the package.json to allow directly selecting of module type during import by forcing a filename.

2022-04-02 22:32 UTC, smeng9 commented
E.g. allow import of react-hook-form/dist/index.cjs.js possible

2022-04-05 00:30 UTC, bluebill1049 commented
Thanks for the detailed explanation. so this is caused by the following usage (CJS import ESM)?

`const HookForm = require("react-hook-form/dist/index.esm.mjs");`

2022-04-05 03:10 UTC, smeng9 commented
Yes, we will have to manually do CJS import ESM to make sure there is only one instance of the package in the compiled code.

2022-04-05 07:21 UTC, bluebill1049 commented
sorry to pull you into this conversation @evocateur wondering if it's safe (none breaking) to introduce this change into the package.json? (any potential side effects) 🙏  many thanks

2022-04-08 17:44 UTC, evocateur commented
@smeng9 The linked roadmap ticket does not seem to indicate this error is being experienced there? Where are you actually experiencing this error? It smells like a Webpack problem, not react-hook-form. If you're using ESM, you have to use `import`, or a bundler that understands it correctly.

@bluebill1049 I am -1 on this change, as it exposes additional public API surface for no perceptible gain. Or, rather, it's "fixing" the issue incorrectly, and if we're truly experiencing this "dual package hazard", we should fix it correctly, instead of hacking it. In my experience, we're almost guaranteed to regret a change like this one in the future, as consumers come to rely on the hacky workaround and become dependent on implementation details.

2022-04-08 17:45 UTC, evocateur requested changes
If we're truly hitting the "dual package hazard" with standard Webpack usage, we should fix the problem correctly, not expose implementation details as "public" API.

2022-04-08 21:17 UTC, smeng9 commented
I will close this PR for now as explained in #8154 as there may be better way to fix the problem mentioned here https://nodejs.org/api/packages.html#approach-1-use-an-es-module-wrapper

2022-04-08 21:17 UTC, closed without merging

2022-04-08 22:15 UTC, bluebill1049 commented
thanks for the feedback and help @evocateur. @smeng9 I don't think it's an issue for the library to resolve. I will reply and close the other issue as well.