fix ref closure may causse memory leak
react-hook-form/react-hook-form pull request #8855
Opened 2022-08-15 12:38 UTC by Z2Y

related #8853

2022-08-15 23:01 UTC, bluebill1049 requested changes
thanks for the pr, could you run the lint fix as well?

2022-08-15 23:01 UTC, bluebill1049 commented on src/utils/createElementRef.ts
> +}
```suggestion
export default (elm: any) => ({
  focus: () => elm.focus(),
  select: () => elm.select(),
  setCustomValidity: (message: string) => elm.setCustomValidity(message),
  reportValidity: () => elm.reportValidity(),
})
```

save few more bytes

2022-08-16 01:49 UTC, bluebill1049 commented on src/useController.ts
> +            field._f.ref = /*#__NOINLINE__*/ createElementRef(elm);
could you remove that comment unless there is a reason for it?

2022-08-16 01:56 UTC, Z2Y commented on src/useController.ts
> +            field._f.ref = /*#__NOINLINE__*/ createElementRef(elm);
Wihout this comment, the createElementRef function will be inlined here, so it will be cause the same problem.

2022-08-16 02:54 UTC, bluebill1049 commented on src/useController.ts
> +            field._f.ref = /*#__NOINLINE__*/ createElementRef(elm);
What's the same problem? as lint error?

2022-08-16 03:09 UTC, Z2Y commented on src/useController.ts
> +            field._f.ref = /*#__NOINLINE__*/ createElementRef(elm);
t._f.ref= function(e) {
  return {
   focus:()=>e.focus(),
   select:()=>e.select(),
   setCustomValidity: t =>e.setCustomValidity(t),
   reportValidity: ()=>e.reportValidity()
 }
}(e)

After build. the output will inline function like this. so it will hold the outer scope too.
you can see the difference of the dist file wihout this comment.

2022-09-30 21:37 UTC, closed without merging