Fix typings for useWatch() with no arguments
react-hook-form/react-hook-form pull request #8923
Opened 2022-08-25 18:26 UTC by brombal

See https://github.com/react-hook-form/react-hook-form/issues/8922

2022-08-25 22:34 UTC, bluebill1049 commented
thanks for the PR 🙏

2022-08-25 22:34 UTC, bluebill1049 approved these changes

2022-08-27 16:04 UTC, Moshyfawn approved these changes

2022-08-27 16:06 UTC, Moshyfawn requested changes
Let me just check the CSB first..

2022-08-27 16:07 UTC, Moshyfawn approved these changes
Alright, thx for spotting that!

2022-08-27 16:30 UTC, merged